title: ProductTO
baseURL: /
params:
  palette: green
  header:
    title: ProductTO
    has_nav: true
    menu:
      actions:
        - label: Apply to Join
          url: /join
  footer:
    tagline: ProductTO
    has_nav: true
    nav_title: Organisation
    has_social: true
    social_title: Community
    has_subscribe: false
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: '&copy; All rights reserved.'
    links:
      - text: Made by Henry Dillon from WIL
        url: 'https://www.wellinformed.co.uk'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
